apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipes-app-github
  labels:
    app: recipes-flask-app
spec:
  selector:
    matchLabels:
        app: recipes-flask-app
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: recipes-flask-app
    spec:
      containers:
        - name: recipes-flask-app
          image: 494142592763.dkr.ecr.us-east-1.amazonaws.com/recipes-flask-app:latest
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Always