apiVersion: v1
kind: Service
metadata:
  name: recipes-flask-app
spec:
  selector:
    app: recipes-flask-app
  type: LoadBalancer # Change this to NodePort or ClusterIP based on your requirements
  ports:
    - protocol: TCP
      port: 80 # Replace with the port on which your application is listening
      targetPort: 80 # Replace with the port on which your application is listening
