on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: Deploy to EKS

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Install and configure AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli
        aws eks update-kubeconfig --name recipes

    - name: Build, tag, and push the image to Amazon ECR
      id: build-image
      env:
        ECR_REPOSITORY: ${{ secrets.REPO_NAME }}
        IMAGE_TAG: latest

      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 494142592763.dkr.ecr.us-east-1.amazonaws.com/$ECR_REPOSITORY
        # Build a docker container and push it to ECR 
        docker build -t public.ecr.aws/a1s4f4e7/$ECR_REPOSITORY:$IMAGE_TAG .
        echo "Pushing image to ECR..."
        docker push public.ecr.aws/a1s4f4e7/$ECR_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

    - name: Deploy application to EKS
      run: |
        kubectl apply -f kubernetes/deployment.yml
        kubectl apply -f kubernetes/service.yml
